# Site settings
title:          "Olivia's blog"
description:    "Hahm's blog"
url:            "https://olivia-yoon.github.io"
baseurl:

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Olivia Yoon
  email:        direktor.y@daum.net

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

remote_theme : chesterhow/tale